add_friend/urls.py
from django.conf.urls import url
from .views import index, new_friend

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^new_friend', new_friend, name='new_friend'),
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import update_status.urls as update_status
import add_friend.urls as add_friend
import profil.urls as profile
import statistik.urls as statistik

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^update-status/', include(update_status, namespace='update-status')),
    url(r'^add-friend/', include(add_friend, namespace='add-friend')),
    url(r'^profile/', include(profile, namespace='profile')),
    url(r'^statistik/', include(statistik, namespace='statistik')),
    url(r'^$', RedirectView.as_view(url='update-status/', permanent=True), name='$  '),
]

profil/urls.py
from django.conf.urls import url
from .views import biodata_table

urlpatterns = [
    url(r'^$', biodata_table, name='biodata_table'),
 ]

statistik/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index')
]

update_status/urls.py
from django.conf.urls import url
from .views import index, add_post, del_post
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_post', add_post, name='add_post'),
	url(r'^del_post/(?P<status_id>\d+)/$', del_post, name='del_post'),
	url(r'^(?P<slug>[\w-]+)/delete/$', del_post),
]

add_friend/models.py
from django.db import models

class Friend(models.Model):
    name = models.CharField(max_length=27)
    url = models.URLField(max_length=200)
    created_date = models.DateTimeField(auto_now_add=True)

profil/models.py
from django.db import models
from django.contrib import admin

class Biodata(models.Model):
		
    name = models.CharField(max_length=27)
    birth = models.DateTimeField()
    sex = models.CharField(max_length=7)
    description = models.TextField()
    email = models.EmailField()
    expertise = models.CharField(max_length=250, default='a,b,c')
    photo = models.TextField(default="https://rosatamarindus.github.io/img/profile.jpg")

statistik/models.py
from django.db import models

# Create your models here.

update_status/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
	created_date = models.DateTimeField(auto_now_add=True)
	description = models.TextField()

add_friend/forms.py
from django import forms

class Add_Friend_Form(forms.Form):
    my_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan url',
    }
    attrs = {
        'class': 'form-control'
    }

    name = forms.CharField(label='Name',required=True, max_length=27, error_messages = my_messages, widget=forms.TextInput(attrs=attrs))
    url = forms.URLField(label='URL',required=True, max_length=200,error_messages = my_messages, widget=forms.TextInput(attrs=attrs))
    #message = forms.CharField(widget=forms.Textarea(attrs=attrs), required=True, error_messages = my_messages)

update_status/forms.py
from django import forms

class  Status_Form(forms.Form):
	description_attrs = {
		'type': 'text',
		'cols': 50,
		'rows': 4,
		'class': 'status-form-textarea',
		'placeholder':'Apa yang Anda pikirkan?'
	}

	description = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

add_friend/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from .forms import Add_Friend_Form
from .models import Friend
from urllib.request import urlopen
from urllib.error import URLError

# Create your views here.
response = {}
def index(request):
	response['author'] = "Hanif" #TODO Implement yourname
	friend = Friend.objects.all()
	response['friend'] = friend
	html = 'add_friend/add_friend.html'
	response['add_friend_form'] = Add_Friend_Form
	return render(request, html, response)

def new_friend(request):
	if(request.method == 'POST' and form.is_valid()):
		response['name'] = request.POST['name']
		response['url'] = request.POST['url']
		friend = Friend(name=response['name'], url=response['url'])
		friend.save()
		return HttpResponseRedirect('/add-friend/')
	else:
		return HttpResponseRedirect('/add-friend/')

def url_is_valid(url):
    try:
        thepage = urlopen(url)
    except URLError as e:
        return False
    else:
        return True

profil/views.py
from django.shortcuts import render
from .models import Biodata

response = {'author': "Farol"}

def biodata_table(request):
	try:
		biodata = Biodata.objects.get(id=1)
		explist = biodata.expertise.split(',')
		response['biodata'] = biodata
		response['explist'] = explist
	except Biodata.DoesNotExist:
		explist = 'Error'
		response['biodata'] = 'Error'
		response['explist'] = explist
	finally:
		html = 'profil/profil.html'
		return render(request, html , response)

statistik/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from update_status.models import Status
from profil.views import biodata_table
from add_friend.models import Friend
from datetime import *

response = {}
def index(request):
	response['author'] = "Rosa Nur Rizky F.T"
	#status = Status.objects.filter()[:1].get()
	#response['status']=status
	status_count = len(Status.objects.all())
	response['status_count'] = status_count

	friend_count = len(Friend.objects.all())
	response['friend_count'] = friend_count

	qs = Status.objects.order_by('-created_date')
	if(len(qs) > 0):
		latest_post = qs[0]
	else:
		latest_post = None

	response['latest_post'] = latest_post

	html = 'statistik/statistik.html'

	return render(request, html, response)

update_status/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from .forms import Status_Form
from .models import Status

# Create your views here.
response = {}
def index(request):    
	response['author'] = "Rosa Nur Rizky F.T" #TODO Implement yourname
	status = Status.objects.all()
	response['status'] = status
	response['status_form'] =  Status_Form
	html = 'update_status/update_status.html'
	return render(request, html, response)

def add_post(request):
	form = Status_Form(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		response['description'] = request.POST['description']
		status = Status(description=response['description'])
		status.save()
		return HttpResponseRedirect('/update-status/')
	else:
		return HttpResponseRedirect('/update-status/')

def del_post(request, status_id):
	instance = Status.objects.get(id=status_id)
	instance.delete()
	return HttpResponseRedirect('/update-status/')

add_friend/templates/add_friend/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="Lingin">
  <meta name="author" content="{{author}}">
  <!-- bootstrap csss -->
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700&amp;lang=en" />
  <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&amp;lang=en" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/add_friend.css' %}" />

  <title>
    {%block title %} Lingin {% endblock %}
  </title>
</head>

<body>
    <header>
        {% include "add_friend/partials/header.html" %}
    </header>
    <content>
        <div class="container">
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
        </div>
    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "add_friend/partials/footer.html" %}
        {% endblock %}
    </footer>
</body>
</html>

add_friend/templates/add_friend/partials/footer.html
<!-- templates/lab_5/partials/footer.html -->
<!-- TODO, CREATE THIS FILE AND ADD copyright symbol -->
<p> &copy; Made with &hearts; in Cibubur by {{author}} </p>

add_friend/templates/add_friend/partials/header.html
<!-- templates/update_status/partials/header.html -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="">Ling In</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <!-- LINK MENUJU Status, Profile, Friends, dan Stats  -->
        <li class="nav-item">
          <a class="nav-link" href="/update-status">Status</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/profile">Profile</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="/add-friend">Friends</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/statistik">Stats</a>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

profil/templates/profil/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Lingin">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700&amp;lang=en" />
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&amp;lang=en" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/profil.css' %}" />
	<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <title>
        {% block title %} Lingin {% endblock %}
    </title>
</head>

<body>
    <header>
        {% include "profil/partials/header.html" %}
    </header>
    <content>
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "profil/partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script type="application/javascript">
      $(function() {
          $('a[href*="#"]:not([href="#"])').click(function() {
            if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
              var target = $(this.hash);
              target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
              if (target.length) {
                $('html, body').animate({
                  scrollTop: target.offset().top - 55
                }, 1000);
                return false;
              }
            }
          });
        });
    </script>

</body>
</html>

profil/templates/profil/partials/footer.html
<!-- templates/lab_5/partials/footer.html -->
<!-- TODO, CREATE THIS FILE AND ADD copyright symbol -->
<p> &copy; Made with &hearts; in Depok by Farolina </p>

profil/templates/profil/partials/header.html
<!-- templates/update_status/partials/header.html -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="">Ling In</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <!-- LINK MENUJU Status, Profile, Friends, dan Stats  -->
        <li class="nav-item">
          <a class="nav-link" href="/update-status">Status</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="/profil">Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/add-friend">Friends</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/statistik">Stats</a>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav> 

profil/templates/profil/profil.html
{% extends "profil/layout/base.html" %}

{% block content %}
<html lang="en">
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body style ="background-image: url(https://images.pexels.com/photos/2255/black-and-white-city-houses-skyline.jpg?w=1200&h=627&fit=crop&auto=compress&cs=tinysrgb);">
	<div class="flex-container" style="font-family: 'Montserrat', sans-serif;">
			<div class="row" style="margin-top: 80px;">
				<div class="column" style="margin-left:30px;">
					<p style="text-align: center"><img src={{biodata.photo}} class="img-circle" alt="" width="200" height="200"></p>
					<div class="row">
						<div class="column">
								<p><b> Skill </b></p>
								<p><big> 50% </big></p>
						</div>
						<div class="column">
								<p><b> Experience </b></p>
								<p><big> 50% </big></p>
						</div>
						<div class="column">
								<p><b> Recruited </b></p>
								<p><big> 13 </big></p>
						</div>
					</div>
					<div class="row" style="align:center">
						<!-- Trigger the modal with a button -->
							<button class="btn btn-lg btn-block btn-info" id="editbutton" data-toggle="modal" data-target="#myModal">Edit Profile</button>
						<!-- Modal -->
							<div class="modal fade" id="myModal" role="dialog">
								<div class="modal-dialog modal-lg">
									<div class="modal-content">
										<div class="modal-header">
											<button type="button" class="close" data-dismiss="modal">&times;</button>
												<h4 class="modal-title">Edit Profile</h4>
										</div>
									<div class="modal-body">
									<form>
										<div class="form-group row">
											<label for="name" class="col-sm-2 col-form-label">Name</label>
											<div class="col-sm-10">
												<input type="text" class="form-control" id="name" value="{{biodata.name}}">
											</div>
										</div>
										<div class="form-group row">
											<label for="description" class="col-sm-2 col-form-label">Description</label>
										<div class="col-sm-10">
											<input type="text" class="form-control" id="description" value="{{biodata.description}}">
										</div>
										</div>
										<div class="form-group row">
											<label for="birthday" class="col-sm-2 col-form-label">Birthdate</label>
										<div class="col-sm-10">
											<input type="text" class="form-control" id="birthdate" value="{{biodata.birth}}">
										</div>
									</div>
										<div class="form-group row">
											<label for="gender" class="col-sm-2 col-form-label">Gender</label>
										<div class="col-sm-10">
											<input type="text" class="form-control" id="gender" value="{{biodata.sex}}">
									</div>
                          </div>
                            <div class="form-group row">
                              <label for="email" class="col-sm-2 col-form-label">Email</label>
                              <div class="col-sm-10">
                                <input type="email" class="form-control" id="email" value="{{biodata.email}}">
                              </div>
                            </div>
                          <div class="form-group row">
                            <label for="expertise" class="col-sm-2 col-form-label">Expertise</label>
                            <div class="col-sm-10">
                              <input type="expertise" class="form-control" id="expertise" value="{{biodata.expertise}}">
                            </div>
                          </div>
                        <div class="form-group row">
                          <label for="photo" class="col-sm-2 col-form-label">Photo Image URL</label>
                          <div class="col-sm-10">
                            <input type="link" class="form-control" id="link" value="{{biodata.photo}}">
                          </div>
                      </div>
                          <div class="form-group row">
                            <div class="col-sm-10" style="float:right">
                              <button type="submit" class="btn btn-lg btn-block btn-info" id="submitbutton">Save</button>
                            </div>
                          </div>
                        </form>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

					</div>
					
				<div class="column" style="margin-left:30px;">
					<h1 align = "left"> {{biodata.name}} </h1>
					<p><big> Front-End Developer </big><p>
					<hr class="style5">
					{% if biodata == 'Error' %}
					<table style="text-align: center">
						
						<tr>
							<th class="subject" align="left"><b>Birthdate</b></th>
							<td class="value" align="left"> biodata </td>
						</tr>
						<tr>
							<td class="subject" align="left"><b>Sex</b></th>
							<td class="value" align="left"> biodata </td>
						</tr> 
						<tr>
							<td class="subject" align="left"><b>Description</b></th>
							<td class="value" align="left"> biodata </td>
						</tr>
						<tr>
							<td class="subject" align="left"><b>Email</b></th>
							<td class="value" align="left"> biodata </td>
						</tr>    					             
					</table>
						{% else %}
					<table style="text-align: center">
						<tr>
							<th class="subject" align="left"><b>Birthdate</b></th>
							<td class="value" align="left"> {{biodata.birth}} </td>
						</tr>
						<tr>
							<td class="subject" align="left"><b>Sex</b></th>
							<td class="value" align="left"> {{biodata.sex}} </td>
						</tr> 
						<tr>
							<td class="subject" align="left"><b>Description</b></th>
							<td class="value" align="left"> {{biodata.description}} </td>
						</tr>
						<tr>
							<td class="subject" align="left"><b>Email</b></th>
							<td class="value" align="left"> {{biodata.email}} </td>
						</tr>    					             
					</table>
					{% endif %}
					<br>
					<p style="text-align: center;"><big><b> Expertise </b></big></p>
					<div class="row">
					{% if expertise == 'Error' %}
						<table style="text-align: center">
							<tr>
								<td class="column" style="text-align:center;">
								<span id="roundframe" class="roundframe">Error</span>
								</td>
							</tr>
						</table>
					{% else %}
						<table style="text-align: center">
							<tr>
								{% for j in explist %}
								<td class="column" style="text-align:center;">
								<span id="roundframe" class="roundframe">{{j}}</span>
								</td>
								{% endfor %}
							</tr>
						</table>
					{% endif %}
					</div>
				</div>
			</div>
			
	</div>	

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

{% endblock %}

statistik/templates/statistik/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Lingin">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700&amp;lang=en" />
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&amp;lang=en" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/statistik.css' %}" />

    <title>
        {% block title %} Lingin {% endblock %}
    </title>
</head>

<body>
    <header>
        {% include "statistik/partials/header.html" %}
    </header>
    <content>
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "statistik/partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

statistik/templates/statistik/statistik.html
{% extends "statistik/layout/base.html" %}

{% block content %}
<section name="my-list" id="my-list">
    <div class="container">
        <div class="pembuat">
            <center><img src="https://rosatamarindus.github.io/img/profile.jpg" class="image-status"></center>
            <div class="p-author" style="margin-bottom:0;">
                <h2>{{author}}</h2>
            </div>
            <div class="info">
                <p>Friends: {{ friend_count }} People</p><br>
                <p>Feed: {{ status_count }} Posts</p><br>
            </div>
        </div>
            <center><h4>Latest Post</h4>
            {% if latest_post is not None %}
            <p>{{ latest_post.status }}</p><br>
            <p>{{ latest_post.created_date }}</p><br>
            </center>
            {% else %}
            <div class="alert alert-danger text-center">
                Oops! Anda belum memposting apapun.
            </div>
            {% endif %}
        </section>

        {% endblock %}

update_status/templates/update_status/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Lingin">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700&amp;lang=en" />
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&amp;lang=en" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/update_status.css' %}" />

    <title>
        {% block title %} Lingin {% endblock %}
    </title>
</head>

<body>
    <header>
        {% include "update_status/partials/header.html" %}
    </header>
    <content>
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "update_status/partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="application/javascript">
      $(function() {
          $('a[href*="#"]:not([href="#"])').click(function() {
            if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
              var target = $(this.hash);
              target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
              if (target.length) {
                $('html, body').animate({
                  scrollTop: target.offset().top - 55
                }, 1000);
                return false;
              }
            }
          });
        });

      $(".to-do-list-delete-button").on("click", function(e) {
        var uid = $(this).data('id');
        location.href="del_post/" + uid;
      });
    </script>

</body>
</html>

update_status/templates/update_status/update_status.html
{% extends "update_status/layout/base.html" %}

{% block content %}

<section name="input-list" id="input-list">

    <div class="container">
        <form id="form" method="POST" action="{% url 'update-status:add_post' %}">
            {% csrf_token %}
            {{ status_form }}
            <div class="post-setting">
                <ul class="sharing-share-box">
                    <li class="upload-image">
                        <div class="button-secondary-small-media">
                            <label class="sharing-share-upload">
                                <span class="svg-icon-wrap"><li-icon aria-hidden="true" type="camera-icon" class="sharing-share-action-media__upload-camera-icon"><svg viewBox="0 0 24 24" width="24px" height="24px" x="0" y="0" preserveAspectRatio="xMinYMin meet" class="artdeco-icon"><g class="large-icon" style="fill: currentColor">
                                    <path d="M21,6H18L16.5,3h-9L6,6H3A1,1,0,0,0,2,7V19a1,1,0,0,0,1,1H21a1,1,0,0,0,1-1V7A1,1,0,0,0,21,6ZM7.36,8l1.5-3h6.28l1.5,3H20v2H16.58a5,5,0,0,0-9.16,0H4V8H7.36Zm7.76,4A3.13,3.13,0,1,1,12,8.88,3.13,3.13,0,0,1,15.13,12ZM4,18V11H7.1a5,5,0,1,0,9.8,0H20v7H4Z"></path>
                                </g></svg></li-icon></span>

                                <span class="sharing-subaction-bar__button-text">
                                  Image
                              </span>
                          </label>
                      </div>
                  </li>
                  <li class="upload-video">
                    <div class="button-secondary-small-media">
                        <label for="uploadElementId" class="sharing-share-action-media__upload-input-label">
                            <span class="svg-icon-wrap"><li-icon aria-hidden="true" type="video-camera-icon" class="sharing-share-action-media__upload-camera-icon"><svg viewBox="0 0 24 24" width="24" height="24" style="" x="0" y="0" preserveAspectRatio="xMinYMin meet"><g class="large-icon" style="fill: currentColor">
                                <path d="M21,5.92a1,1,0,0,0-.57.18L17,8.5V7a1,1,0,0,0-1-1H3A1,1,0,0,0,2,7V17a1,1,0,0,0,1,1H16a1,1,0,0,0,1-1V15.5l3.43,2.4a1,1,0,0,0,.57.18,1,1,0,0,0,1-1V6.92A1,1,0,0,0,21,5.92ZM15,16H4V8H15v8Zm2-5.21,3-2.1v6.62l-3-2.1V10.79Z"></path>
                            </g></svg></li-icon>
                        </span>
                        <span class="sharing-subaction-bar__button-text">Video</span>
                    </label>
                </div>
            </li>
        </ul>
        <input id="submit" type="submit" class="button-info" value="Post">
    </div>
    <br>
</form>
</div>
</section>

<section name="my-list" id="my-list">
    <div class="container">
        <h2 class="my-list-title"></h2>
        <div class="flex">
            {% if status %}
            {% for data in status %}
            <div class="flex-item">
                <div class="to-do-list">
                    <div class="pembuat">
                        <img src="https://rosatamarindus.github.io/img/profile.jpg" class="image-status">
                        <div class="p-author">
                            <div class="to-do-list-author">
                                {{author}}
                            </div>
                            <br>
                            <div class="to-do-list-date-added">
                                {{data.created_date}}
                            </div>
                        </div>

                    </div>

                    <div class="to-do-list-description">
                        {{data.description}}
                    </div>
                    <div class="to-do-list-delete">
                        <div class="to-do-list-delete-button" data-id="{{data.id}}">Delete</div>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Oops!</strong> Anda belum memposting apapun.
            </div>
            {% endif %}
        </div>
    </div>
</section>

{% endblock %}        